// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDem2Q7dHXshEPuhdLdrZbuSpnAmJl6DSg',
    appId: '1:466214967044:web:15ed0f42d259f6ff6ea251',
    messagingSenderId: '466214967044',
    projectId: 'campus-chat-c8499',
    authDomain: 'campus-chat-c8499.firebaseapp.com',
    storageBucket: 'campus-chat-c8499.firebasestorage.app',
    measurementId: 'G-32VZRNX15V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNy7EGHf3tzxZ8AXUUqj5xjLsGOmkcAjk',
    appId: '1:466214967044:android:146b2cc981b3e8806ea251',
    messagingSenderId: '466214967044',
    projectId: 'campus-chat-c8499',
    storageBucket: 'campus-chat-c8499.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC692tcJqHXlCtC1s0mDrwxDDoc2coUwwM',
    appId: '1:466214967044:ios:31dd17ee9bf77e126ea251',
    messagingSenderId: '466214967044',
    projectId: 'campus-chat-c8499',
    storageBucket: 'campus-chat-c8499.firebasestorage.app',
    iosBundleId: 'com.example.campusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC692tcJqHXlCtC1s0mDrwxDDoc2coUwwM',
    appId: '1:466214967044:ios:31dd17ee9bf77e126ea251',
    messagingSenderId: '466214967044',
    projectId: 'campus-chat-c8499',
    storageBucket: 'campus-chat-c8499.firebasestorage.app',
    iosBundleId: 'com.example.campusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDem2Q7dHXshEPuhdLdrZbuSpnAmJl6DSg',
    appId: '1:466214967044:web:d8f6c6febc4bc6536ea251',
    messagingSenderId: '466214967044',
    projectId: 'campus-chat-c8499',
    authDomain: 'campus-chat-c8499.firebaseapp.com',
    storageBucket: 'campus-chat-c8499.firebasestorage.app',
    measurementId: 'G-PVHZ7CKSQZ',
  );
}
